### ISSUE TITLE
Cannot parse GALX out of login page

### ISSUE THREAD

**Issue by gosom** [suryasev/unofficial-google-trends-api#3]
Hello,
 a small bug:
Sometimes the connector raises the above exception.

The regex you use is ; 
(?P<galx>[a-zA-Z0-9_]+)

but with the html below does not find any matches

type="hidden" name="GALX" value="-jMistC0wtQ"

I change the regex to 
(?P<galx>[a-zA-Z0-9_-]+)

(added - ) and it seems to work now.

Thanks for the module

**Comment by suryasev** [comment]
Thanks gosom!  I just added your fix.
